### ISSUE TITLE
What layout for tablet/desktop?

### ISSUE THREAD

**Issue by jeanbaptistedeborman** [jeanbaptistedeborman/pacman#18]
Is there any difference between tablet and desktop? I would think:
-Desktop: the game is not scaled and fits under the Europa banner.
-Tablet: the game goes fullscreen (as my app does now).

**Comment by Nostok** [comment]
Email discussion with GK.

GK: What do you mean by that? The tablet/desktop are the same.  Mobile is a different game.
JB: My question is precisely (as stated in a previous mail):
Is there any layout difference between tablet and desktop? I would propose:
-Desktop: the game is not scaled and fits under the Europa banner.
-Tablet: the game goes fullscreen (as my app does now).

Let me stress stress that usability on tablet would be way better with the game in full screen because it would prevent scrolls and other unwanted touch-interactions.

Last time we spoke, PM said my proposal made sense but needed to be discussed with the client. So, I am waiting for some confirmation. 
On the other hand, I do not absolutely need an answer :  I can simply deliver an application that will fill any HTML container (whatever the size), which would leave you the freedom to use any option. 
GK: OK (regarding deliver the application that will fill any HTML container).

**Comment by jeanbaptistedeborman** [comment]
For the demo, it would be good to have it in the EU container so they see how it displays.

**Comment by jeanbaptistedeborman** [comment]
Integration in Europa template: 
http://linguagopreview.azurewebsites.net/index_europa.htm
But questions remain. See: https://github.com/jeanbaptistedeborman/pacman/issues/75
